on:
  push:
    branches:
    - main

jobs:
  frontend: 
    name: Build frontend
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd frontend 
          docker build -t frontend:${{ github.sha }} .

      - name: Tag the image
        run: |
          docker tag frontend:${{ github.sha }} ghcr.io/ranper85/guest2-frontend:${{ github.sha }}
          docker tag frontend:${{ github.sha }} ghcr.io/ranper85/guest2-frontend:latest

      - name: Login to GHCR
        run: docker login --username ranper85 --password ${{ Secrets.DOCKER_TOKEN }} ghcr.io

      - name: Push the images
        run: |
          docker push ghcr.io/ranper85/guest2-frontend:${{ github.sha }}
          docker push ghcr.io/ranper85/guest2-frontend:latest


  backend:
    name: Build backend
    runs-on: ubuntu-22.04
  

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd backend
          docker build -t backend:${{ github.sha }} .

      - name: Tag
        run: |
          docker tag backend:${{ github.sha }} ghcr.io/ranper85/guest2-backend:${{ github.sha }}
          docker tag backend:${{ github.sha }} ghcr.io/ranper85/guest2-backend:latest

      - name: Login to GHCR
        run: docker login ghcr.io -u ranper85 -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push
        run: |
          docker push ghcr.io/ranper85/guest2-backend:${{ github.sha }}
          docker push ghcr.io/ranper85/guest2-backend:latest


  
  frontend-deployment:
    name: frontend-deployment
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: deployment
        run: |
          pwd
          ls
      - name: oc login
        run: oc login --token=${{ secrets.OCP_TOKEN }} --insecure-skip-tls-verify --server=https://api.devops24.cloud2.se:6443
      - name: oc project
        run: oc project rani
      - name: oc apply
        run: 
          oc apply -f frontend-deployment.yaml

      

 
          

       
      
