on:
  push:
    branches:
    - main

jobs:
  frontend: 
    name: Build frontend
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd frontend 
          docker build -t frontend:${{ github.sha }} .

      - name: Tag the image
        run: |
          docker tag frontend:${{ github.sha }} ghcr.io/ranper85/guest2-frontend:${{ github.sha }}
          docker tag frontend:${{ github.sha }} ghcr.io/ranper85/guest2-frontend:latest

      - name: Login to GHCR
        run: docker login --username ranper85 --password ${{ Secrets.DOCKER_TOKEN }} ghcr.io

      - name: Push the images
        run: |
          docker push ghcr.io/ranper85/guest2-frontend:${{ github.sha }}
          docker push ghcr.io/ranper85/guest2-frontend:latest





      

 
          

       
      
